language: java

before_install:
  - brew tap caskroom/cask
  - brew install brew-cask python python3
  - brew cask update
  - brew cask install astah-community
  
script: mvn test -f ./simpleocl/pom.xml
