language: objective-c  # Do tests on OS X
env:
  global:
    - SKIP_IMAGE_CHECK=1
before_install:
  - brew update
  - brew cask install java
  - brew cask install astah-community
  - curl -O http://cdn.change-vision.com/files/astah-professional-7_1_0-f2c212.zip
  - unzip astah*.zip
  - cd astah-professional/
  - ls -la
script: mvn test -PCommunity -f ./simpleocl/pom.xml
